### ISSUE TITLE
Lab instructions differ from what the test is looking for

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/OO-Vehicle#7]
User: Amitai Blickstein

Batch: ios-0615

Current Lesson: Inheritance Practice

Location: https://learn.co/tracks/ios-pre-work/objects-in-objective-c/inheritance/inheritance-practice?track_id=582&batch_id=62

Bug Description: Content issue: The lab instructs to use NSIntegers, but the tests look for NSNumber literals.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by markedwardmurray** [comment]
resolved by https://github.com/learn-co-curriculum/OO-Vehicle/pull/8
